project:
  type: website

website:
  title: "IS415-GAA-WY"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Hands on exercises"
        menu: 
        - text: "Hands-on exercise 1"
          href: lessons/lesson2/lesson2_handson.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

