project:
  type: website

website:
  title: "IS415-GAA-WY"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Hands-on exercises"
        menu: 
        - text: "Hands-on exercise 1"
          href: lessons/lesson2/lesson2_handson.qmd
        - text: "Hands-on exercise 2"
          href: handson-ex/lesson3/hands-on-ex3.qmd
        - text: "Hands-on exercise 3"
          href: handson-ex/lesson4/handson-ex4.qmd
        - text: "Hands-on exercise 7"
          href: handson-ex/lesson7/handson-ex07.qmd
        - text: "Hands-on exercise 8"
          href: handson-ex/lesson8/handson-ex8.qmd
      - text: "In-class Exercise"
        menu: 
        - text: "In-class exercise 2"
          href: lessons/lesson2/in-class-ex2.qmd
        - text: "In-class exercise 3"
          href: inclass-ex/inclass_ex03/inclass_ex03.qmd
        - text: "In-class exercise 4"
          href: inclass-ex/inclass-ex04/inclass_ex04.qmd
        - text: "In-class exercise 5"
          href: inclass-ex/inclass-ex05/inclass_ex05.qmd
        - text: "In-class exercise 6"
          href: inclass-ex/inclass-ex06/inclass-ex06.qmd
        - text: "In-class exercise 7"
          href: inclass-ex/inclass-ex07/inclass-ex07.qmd
      - text: "Take-Home Exercise"
        menu: 
        - text: "Take-Home Exercise 1"
          href: take-home-ex/take-home-ex01/take-home-ex01.qmd
        - text: "Take-Home Exercise 2"
          href: take-home-ex/take-home-ex02/take-home-ex02.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

