project:
  type: website

website:
  title: "IS415-GAA-WY"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Hands-on exercises"
        menu: 
        - text: "Hands-on exercise 1"
          href: lessons/lesson2/lesson2_handson.qmd
      - text: "In-class Exercise"
        menu: 
        - text: "In-class exercise 2"
          href: lessons/lesson2/in-class-ex2.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

