---
title: "In-class Exercise 4"
author: "Wen Yang"
date: "30 January 2023"
format: html
date-modified: "`r Sys.Date()`"
number-sections: true

execute:
  message: true
  warning: false
  echo: true
  eval: true
  
editor: visual
---

### Loading the package

```{r}
pacman::p_load(maptools, sf, raster, spatstat, tmap)
```

Things to learn from the code chunk

### Importing Data

```{r}
childcare_sf <- st_read("data/childcare.geojson") %>%
  st_transform(crs = 3414)
```

```{r}
sg_sf <- st_read(dsn = "data", layer="CostalOutline")
```

```{r}
mpsz_sf <- st_read(dsn = "data", 
                layer = "MP14_SUBZONE_WEB_PL")
```

```{r}
tmap_mode('view')
tm_shape(childcare_sf)+
  tm_dots()
```

#### Convert from Shape File to Spatial Feature File

```{r}
childcare <- as_Spatial(childcare_sf)
mpsz <- as_Spatial(mpsz_sf)
sg <- as_Spatial(sg_sf)
```

#### Convert from Spatial Feature to Generic

```{r}
childcare_sp <- as(childcare, "SpatialPoints")
sg_sp <- as(sg, "SpatialPolygons")
```

#### Convert to PPP format (Spatstat)

Cos for points they need x y coordinates

```{r}
childcare_ppp <- as(childcare_sp, "ppp")
childcare_ppp
```
