---
title: "Untitled"
---

```{r}
pacman::p_load(sf ,tidyverse, tmap, DT)
```

```{r}
sg_map_polygon <- st_read(dsn="data/geospatial", layer="MP14_SUBZONE_WEB_PL")
sg_residential_pop <- read_csv("data/aspatial/respopagesextod2011to2020.csv")
```

```{r}
sg_residential_pop_2020 <- sg_residential_pop %>%
  filter(Time == 2019) %>%
  group_by(PA, SZ, AG) %>%
  summarise(`POP` = sum(`Pop`)) %>%
  ungroup()%>%
  pivot_wider(names_from=AG, 
              values_from=POP) %>%
  mutate(YOUNG = rowSums(.[3:6])
         +rowSums(.[12])) %>%
mutate(`ECONOMY ACTIVE` = rowSums(.[7:11])+
rowSums(.[13:15]))%>%
mutate(`AGED`=rowSums(.[16:21])) %>%
mutate(`TOTAL`=rowSums(.[3:21])) %>%  
mutate(`DEPENDENCY` = (`YOUNG` + `AGED`)
/`ECONOMY ACTIVE`) %>%
  select(`PA`, `SZ`, `YOUNG`, 
       `ECONOMY ACTIVE`, `AGED`, 
       `TOTAL`, `DEPENDENCY`)
```

```{r}
sg_residential_pop_2020 <- sg_residential_pop_2020 %>%
  mutate_at(.vars = vars(PA, SZ), 
          .funs = funs(toupper)) %>%
  filter(`ECONOMY ACTIVE` > 0)

mpsz_pop2020 <- left_join(sg_map_polygon, sg_residential_pop_2020,
                          by = c("SUBZONE_N" = "SZ"))
```

```{r}
tmap_mode("view")+
  tm_shape(mpsz_pop2020)+
  tm_borders(alpha=0.5)+
  tm_polygons("DEPENDENCY", n=8, style="pretty", id="SUBZONE_N", palette="Reds")
```
