```{r}
pacman::p_load(sf, tidyverse)

mpsz = st_read(dsn = "data/geospatial", 
                  layer = "MP14_SUBZONE_WEB_PL")

cyclingpath = st_read(dsn = "data/geospatial/CyclingPath_Jun2022", layer= "CyclingPathGazette")

preschool = st_read("data/geospatial/preschools-location.kml")

st_geometry(mpsz)
glimpse(mpsz)
head(mpsz, n=5)
```

### Plotting MPSZ

```{r}
plot(mpsz)
```

```{r}
plot(st_geometry(mpsz))
```

```{r}
plot(mpsz["PLN_AREA_N"])
```

```{r}
st_crs(mpsz)
mpsz3414 <- st_set_crs(mpsz, 3414)
```

```{r}
preschool3414 <- st_transform(preschool, crs=3414)
preschool3414
```

### Importing ASpatial Data

```{r}
listings <- read_csv("data/aspatial/listings.csv")
list(listings)
```

```{r}
listings_sf <- st_as_sf(listings, coords = c("longitude", "latitude"), crs=4326) %>%
  st_transform(crs=3414)
```

```{r}
glimpse(listings_sf)
```

### Buffering

```{r}
buffer_cycling <- st_buffer(cyclingpath, dist=5, nQuadSegs=30)
buffer_cycling$AREA <- st_area(buffer_cycling)
sum(buffer_cycling$AREA)
```

### Point-in-polygon count

```{r}
mpsz3414$`PreSch Count`<- lengths(st_intersects(mpsz3414, preschool3414))
summary(mpsz3414$`PreSch Count`)
```

#### Calculate density of pre-school by planning subzone

```{r}
mpsz3414$Area <- mpsz3414 %>%
  st_area()

mpsz3414 <- mpsz3414 %>%
  mutate(`PreSch Density` = `PreSch Count`/Area * 1000000)
```

```{r}
```

`` {summary(mpsz3414$`PreSch Density`)} ``

### Exploratory Data Analysis

```{r}
hist(mpsz3414$`PreSch Density`)
```

```{r}
ggplot(data=mpsz3414, 
       aes(x= as.numeric(`PreSch Density`)))+
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue") +
  labs(title = "Are pre-school even distributed in Singapore?",
       subtitle= "There are many planning sub-zones with a single pre-school, on the other hand, \nthere are two planning sub-zones with at least 20 pre-schools",
      x = "Pre-school density (per km sq)",
      y = "Frequency")
```

#### **Scatterplot showing the relationship between Pre-school Density and Pre-school Count**

```{r}
ggplot(data=mpsz3414, 
       aes(y = `PreSch Count`, 
           x= as.numeric(`PreSch Density`)))+
  geom_point(color="black", 
             fill="light blue") +
  xlim(0, 40) +
  ylim(0, 40) +
  labs(title = "",
      x = "Pre-school density (per km sq)",
      y = "Pre-school count")
```

#### 
